package org.example;

import com.fasterxml.jackson.annotation.JacksonAnnotationsInside;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private WarehouseRepository warehouseRepository;
	@Autowired
	private ProductRepository productRepository;
	@Autowired
	private PurchaseRepository purchaseRepository;
	@Autowired
	private LlmService llmService;


	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {

		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	// 1. Collect all data of one warehouse
	@GetMapping("/{warehouseID}")
	@ResponseBody
	public Optional<Warehouse> getWarehouse(@PathVariable String warehouseID) {
		return warehouseRepository.findByWarehouseID(warehouseID);
	}

	// 2. Collect single product of a warehouse
	@GetMapping("/{warehouseID}/product/{productID}")
	@ResponseBody

	public Optional<Product> getProduct(@PathVariable String warehouseID,
										@PathVariable String productID) {
		return productRepository
				.findByWarehouse_WarehouseIDAndProductID(warehouseID, productID);
	}

	// 3. Update warehouse
	@PutMapping("/{warehouseID}")
	@ResponseBody

	public String updateWarehouse(@PathVariable String warehouseID,
								  @RequestParam String city) {

		Optional<Warehouse> warehouse =
				warehouseRepository.findByWarehouseID(warehouseID);

		if (warehouse.isPresent()) {
			Warehouse w = warehouse.get();
			w.setWarehouseCity(city);
			warehouseRepository.save(w);
			return "Updated";
		}

		return "Warehouse not found";
	}


	@GetMapping("/forecast")
	@ResponseBody
	public String forecast() {

		StringBuilder salesData = new StringBuilder();

		purchaseRepository.findAll().forEach(p ->
				salesData.append(
						"Warehouse: " + p.getWarehouse().getWarehouseID()
								+ ", Product: " + p.getProduct().getProductName()
								+ ", Amount: " + p.getAmount()
								+ ", Date: " + p.getPurchaseTime()
								+ "\n"
				)
		);

		return llmService.generateForecast(salesData.toString());
	}

}
